# Generated by Django 4.2.8 on 2023-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=255)),
                ('currency_uom_id', models.CharField(default='USD', max_length=3)),
                ('sales_channel_enum_id', models.CharField(default='ScWeb', max_length=10)),
                ('status_id', models.CharField(default='OrderPlaced', max_length=20)),
                ('product_store_id', models.CharField(default='OMS_DEFAULT_STORE', max_length=20)),
                ('placed_date', models.DateField()),
                ('approved_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyId', models.CharField(max_length=255)),
                ('pseudoId', models.CharField(max_length=255)),
                ('partyTypeEnumId', models.CharField(max_length=255)),
                ('ownerPartyId', models.CharField(max_length=255)),
                ('organizationName', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('maritalStatusEnumId', models.CharField(blank=True, max_length=255, null=True)),
                ('roleTypeId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('party_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('party_type_enum_id', models.CharField(default=None, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=255)),
                ('productTypeEnumId', models.CharField(max_length=255)),
                ('assetTypeEnumId', models.CharField(max_length=255)),
                ('assetClassEnumId', models.CharField(max_length=255)),
                ('chargeShipping', models.CharField(max_length=1)),
                ('returnable', models.CharField(max_length=1)),
                ('productName', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ownerPartyId', models.CharField(max_length=255)),
            ],
        ),
    ]
