# Generated by Django 4.2.8 on 2023-12-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='firstName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='lastName',
            new_name='marital_status_enum_id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='maritalStatusEnumId',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='middleName',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='ownerPartyId',
            new_name='owner_party_id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='partyId',
            new_name='party_id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='partyTypeEnumId',
            new_name='party_type_enum_id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='pseudoId',
            new_name='pseudo_id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='roleTypeId',
            new_name='role_type_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='assetClassEnumId',
            new_name='asset_class_Enum_Id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='assetTypeEnumId',
            new_name='asset_type_enum_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='chargeShipping',
            new_name='charge_shipping',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ownerPartyId',
            new_name='owner_party_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productTypeEnumId',
            new_name='product_type_enum_id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='organizationName',
        ),
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='first_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='myapp.order')),
            ],
        ),
    ]
